import {getComment} from './data-comments.js';

export const getFilm = () => ({
  title: [
    `The Shawshank Redemption`,
    `The Godfather`,
    `The Dark Knight`,
    `12 Angry Men`,
    `Schindler's List`,
    `The Lord of the Rings`,
    `Pulp Fiction`,
    `Il buono, il brutto, il cattivo`,
    `Fight Club`,
    `Forrest Gump`,
    `Inception`,
    `The Matrix`,
    `Goodfellas`,
    `Se7en`,
    `Shichinin no samurai`,
  ] [Math.floor(Math.random() * 15)],
  rating: Math.floor(Math.random() * (10 - 6)) + 6,
  date: new Date((Math.floor(Math.random() * (2019 - 1960)) + 1960), (Math.floor(Math.random() * (12 - 1)) + 1), (Math.floor(Math.random() * (31 - 1)) + 1)),
  duration: `${Math.floor(Math.random() * (2 - 1)) + 1}h ${Math.floor(Math.random() * (60 - 0)) + 0}min`,
  genres: [
    `Crime`,
    `Drama`,
    `Mystery`,
    `Romance`,
    `Comedy`,
    `Film-Noir`,
  ],
  nameImage: [
    `made-for-each-other.png`,
    `popeye-meets-sinbad.png`,
    `sagebrush-trail.jpg`,
    `santa-claus-conquers-the-martians.jpg`,
    `the-dance-of-life.jpg`,
    `the-great-flamarion.jpg`,
    `the-man-with-the-golden-arm.jpg`,
  ] [Math.floor(Math.random() * 7)],
  description: [
    `Lorem ipsum dolor sit amet, consectetur adipiscing elit.`,
    `Cras aliquet varius magna, non porta ligula feugiat eget.`,
    `Fusce tristique felis at fermentum pharetra.`,
    `Aliquam id orci ut lectus varius viverra.`,
    `Nullam nunc ex, convallis sed finibus eget, sollicitudin eget ante.`,
    `Phasellus eros mauris, condimentum sed nibh vitae, sodales efficitur ipsum.`,
    `Sed blandit, eros vel aliquam faucibus, purus ex euismod diam, eu luctus nunc ante ut dui.`,
    `Sed sed nisi sed augue convallis suscipit in sed felis.`,
    `Aliquam erat volutpat.`,
    `Nunc fermentum tortor ac porta dapibus.`,
    `In rutrum ac purus sit amet tempus.`,
  ] [Math.floor(Math.random() * 11)],
  director: [
    `Frank Darabont`,
    `Francis Ford Coppola`,
    `Christopher Nolan`,
    `Sidney Lumet`,
    `Quentin Tarantino`,
  ] [Math.floor(Math.random() * 5)],
  writers: [
    ` Anne Wigton`,
    ` Heinz Herald`,
    ` Richard Weil`,
    ` Quentin Tarantino`,
    ` Christopher Markus`,
    ` Stephen McFeely`,
    ` Joon-ho Bong`,
  ].splice((Math.floor(Math.random() * (3 - 0)) + 0), (Math.floor(Math.random() * (4 - 2)) + 2)),
  actors: [
    ` Leonardo DiCaprio`,
    ` Brad Pitt`,
    ` Margot Robbie`,
    ` Robert Downey Jr.`,
    ` Chris Evans`,
    ` Mark Ruffalo`,
    ` Kang-ho Song`,
    ` Sun-kyun Lee`,
  ].splice((Math.floor(Math.random() * (3 - 0)) + 0), (Math.floor(Math.random() * (4 - 2)) + 2)),
  country: [
    `USA`,
    `Mexico`,
    `England`,
    `Russia`,
  ] [Math.floor(Math.random() * 4)],
  isWatchlist: Boolean(Math.round(Math.random())),
  isHistory: Boolean(Math.round(Math.random())),
  isFavorites: Boolean(Math.round(Math.random())),
  ratingFilm: Math.floor(Math.random() * (9 - 1)) + 1,
  arrayComments: new Array(4).fill(``).map(getComment),
  // comments: Math.floor(Math.random() * (300 - 10)) + 10,
});
